build:
  image: ensime/ensime:latest
      
  commands:
    - export NVM_DIR="$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git $NVM_DIR && cd $NVM_DIR && git checkout `git describe --abbrev=0 --tags`
    - . $NVM_DIR/nvm.sh
    - nvm install $$NODE_VERSION
    - nvm use $$NODE_VERSION
    - cd $DRONE_DIR
    - rm -rf node_modules
    - npm install --unsafe-perm
    - curl http://ensime.typelevel.org/ensime_2.11-1.0.0-assembly.jar -o $DRONE_DIR/ensime_2.11-1.0.0-assembly.jar
    - export ENSIME_ASSEMBLY_JAR=$DRONE_DIR/ensime_2.11-1.0.0-assembly.jar
    - npm run it

matrix:
  NODE_VERSION:
    - 5

cache:
  mount:
    - .git
