language: scala
scala:
  - 2.11.11
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      env: NODE_VERSION="6"
    - os: linux
      jdk: oraclejdk8
      env: NODE_VERSION="7"
    - os: osx
      osx_image: xcode8
      env: NODE_VERSION="6"
    - os: osx
      osx_image: xcode8
      env: NODE_VERSION="7"
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
    source /tmp/.nvm/nvm.sh;
    nvm install $NODE_VERSION;
    nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install
script:
  - npm run lint
  - npm run test
  
notifications:
  email:
    recipients: 
      - hedefalk@gmail.com
    on_success: change
    on_failure: always
    
